=== kovacsgergely22/Notes/Web/XML_Mastery-Unleashing _the_powe_of_data_markup-Udemy/examples/XML_Schema/1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="EmloyeeDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Employee" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="Name" type="xs:string"></xs:element>
                            <xs:element name="Age" type="xs:int"></xs:element>
                            <xs:element name="Sex" type="xs:string"></xs:element>
                            <xs:element name="City" type="xs:string"></xs:element>
                            <xs:element name="PhNo" type="xs:decimal"></xs:element>
                            <xs:element name="Salary" type="xs:decimal"></xs:element>
                        </xs:all>
                        <xs:attribute name="EmpId" type="xs:ID" use="required"></xs:attribute>
                        <xs:attribute name="Desig" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kovacsgergely22/Notes/Web/XML_Mastery-Unleashing _the_powe_of_data_markup-Udemy/examples/XML_Schema/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<EmloyeeDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1.xsd">
    <Employee EmpId="E001" Desig="Software">
        <Name>Mr. John</Name>
        <Sex>Male</Sex>
        <Age>25</Age>
        <City>Mumbai</City>
        <PhNo>1234567890</PhNo>
        <Salary>5678.89</Salary>
    </Employee>
    <Employee EmpId="E002" Desig="Testing">
        <Name>Mr. ABC</Name>
        <Sex>Male</Sex>
        <Age>30</Age>
        <City>Pune</City>
        <PhNo>1234567890</PhNo>
        <Salary>5000.67</Salary>
    </Employee>
</EmloyeeDetails>
