=== kovacsgergely22/Notes/Web/XML_Mastery-Unleashing _the_powe_of_data_markup-Udemy/examples/XML_Schema/2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="EmployeeDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Employee" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"></xs:element>
                            <xs:element name="Age" type="xs:int"></xs:element>
                            <xs:element name="Gender" type="xs:string"></xs:element>
                            <xs:element name="City" type="xs:string"></xs:element>
                            <xs:element name="PhNo" type="xs:decimal"></xs:element>
                            <xs:element name="Salary" type="xs:decimal"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="EmpID" type="xs:ID" use="required"></xs:attribute>
                        <xs:attribute name="Design" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kovacsgergely22/Notes/Web/XML_Mastery-Unleashing _the_powe_of_data_markup-Udemy/examples/XML_Schema/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<EmployeeDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="2.xsd">
    <Employee EmpID="E001" Design="Software">
        <Name>Mr. John</Name>
        <Age>25</Age>
        <Gender>Male</Gender>
        <City>Mumbai</City>
        <PhNo>1234567890</PhNo>
        <Salary>50000</Salary>
    </Employee>
    <Employee EmpID="E002" Design="Tester">
    <Name>Schweta</Name>
    <Age>29</Age>
    <Gender>Female</Gender>
    <City>Bangalore</City>
    <PhNo>9865467864</PhNo>
    <Salary>8787.9</Salary>
    </Employee>
</EmployeeDetails>
