=== kovacsgergely22/Notes/Web/XML_ME/Webes_adatkezelo_kornyezetek/Feleves_feladat/XSDmktjs0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="oktatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tanulok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tanulo" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string"></xs:element>
                                        <xs:element name="szulIdo" type="xs:date"></xs:element>
                                        <xs:element name="lakcim">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="irsz" type="xs:int"></xs:element>
                                                    <xs:element name="varos" type="xs:string"></xs:element>
                                                    <xs:element name="utca" type="xs:string"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="felhID" type="xs:decimal" use="required"></xs:attribute>
                                    <xs:attribute name="felhnev" type="xs:string" use="required"></xs:attribute>
                                    <xs:attribute name="olvID" type="xs:decimal" use="required"></xs:attribute>
                                    <xs:attribute name="eolvID" type="xs:decimal" use="required"></xs:attribute>
                                    <xs:attribute name="onkurzusID" type="xs:decimal" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="felh-key">
                        <xs:selector xpath="tanulo"></xs:selector>
                        <xs:field xpath="@felhID"></xs:field>
                    </xs:key>
                    <xs:key name="olvas-key">
                        <xs:selector xpath="tanulo"></xs:selector>
                        <xs:field xpath="@olvID"></xs:field>
                    </xs:key>
                    <xs:unique name="felhnev-un">
                        <xs:selector xpath="tanulo"></xs:selector>
                        <xs:field xpath="@felhnev"></xs:field>
                    </xs:unique>
                </xs:element>
                <xs:element name="konyvek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="konyv" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="szerzo" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
                                        <xs:element name="cim" type="xs:string"></xs:element>
                                        <xs:element name="kiado" type="xs:string"></xs:element>
                                        <xs:element name="megjelenEv" type="xs:gYear"></xs:element>
                                        <xs:element name="kategoria" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="kID" type="xs:decimal" use="required"></xs:attribute>
                                    <xs:attribute name="nyID" type="xs:decimal" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="konyv-key">
                        <xs:selector xpath="konyvek"></xs:selector>
                        <xs:field xpath="@kID"></xs:field>
                    </xs:key>
                    <xs:keyref name="konyvnyelv-ref" refer="nyelv-key">
                        <xs:selector xpath="oktatas/nyelvek/nyelv"></xs:selector>
                        <xs:field xpath="@nyID"></xs:field>
                    </xs:keyref>
                </xs:element>
                <xs:element name="olvasas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="olvas" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="kezdete" type="xs:date"></xs:element>
                                        <xs:element name="vege" type="xs:date"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="olvasID" type="xs:decimal" use="required"></xs:attribute>
                                    <xs:attribute name="felhID" type="xs:decimal" use="required"></xs:attribute>
                                    <xs:attribute name="kID" type="xs:decimal" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="olvasas-key">
                        <xs:selector xpath="olvas"></xs:selector>
                        <xs:field xpath="@olvasID"></xs:field>
                    </xs:key>
                    <xs:keyref name="felh-olvas-ref" refer="felh-key">
                        <xs:selector xpath="oktatas/tanulok/tanulo"></xs:selector>
                        <xs:field xpath="@felhID"></xs:field>
                    </xs:keyref>
                </xs:element>
                <xs:element name="eolvasas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ebook" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="szerzo" type="xs:string"></xs:element>
                                        <xs:element name="cim" type="xs:string"></xs:element>
                                        <xs:element name="kiado" type="xs:string"></xs:element>
                                        <xs:element name="megjelenEv" type="xs:gYear" minOccurs="0" maxOccurs="1"></xs:element>
                                        <xs:element name="link" type="xs:anyURI"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="eID" type="xs:decimal" use="required"></xs:attribute>
                                    <xs:attribute name="nyID" type="xs:decimal" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="e-key">
                        <xs:selector xpath="eolvasas"></xs:selector>
                        <xs:field xpath="@eID"></xs:field>
                    </xs:key>
                    <xs:keyref name="enyelv-ref" refer="nyelv-key">
                        <xs:selector xpath="oktatas/nyelvek/nyelv"></xs:selector>
                        <xs:field xpath="@nyID"></xs:field>
                    </xs:keyref>
                </xs:element>
                <xs:element name="onkurzusok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="onkurzus" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cim" type="xs:string"></xs:element>
                                        <xs:element name="kiado" type="xs:string"></xs:element>
                                        <xs:element name="megjelenEv" type="xs:gYear" minOccurs="0" maxOccurs="1"></xs:element>
                                        <xs:element name="link" type="xs:anyURI"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="oID" type="xs:decimal" use="required"></xs:attribute>
                                    <xs:attribute name="nyID" type="xs:decimal" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="onkurzus-key">
                        <xs:selector xpath="onkurzus"></xs:selector>
                        <xs:field xpath="@oID"></xs:field>
                    </xs:key>
                    <xs:keyref name="onkurzusnyelv-ref" refer="nyelv-key">
                        <xs:selector xpath="oktatas/nyelvek/nyelv"></xs:selector>
                        <xs:field xpath="@nyID"></xs:field>
                    </xs:keyref>
                </xs:element>
                <xs:element name="oktatok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="oktato" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string"></xs:element>
                                        <xs:element name="email" type="xs:string"></xs:element>
                                        <xs:element name="weboldal" type="xs:anyURI"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="oktID" type="xs:decimal" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="oktato-key">
                        <xs:selector xpath="oktato"></xs:selector>
                        <xs:field xpath="@oktID"></xs:field>
                    </xs:key>
                </xs:element>
                <xs:element name="nyelvek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nyelv" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nev" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nyID" type="xs:decimal" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="nyelv-key">
                        <xs:selector xpath="nyelv"></xs:selector>
                        <xs:field xpath="@nyID"></xs:field>
                    </xs:key>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kovacsgergely22/Notes/Web/XML_ME/Webes_adatkezelo_kornyezetek/Feleves_feladat/XMLmktjs0.xml
<?xml version="1.0" encoding="UTF-8"?>
<oktatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDmktjs0.xsd">
    <tanulok>
        <tanulo felhID="1" felhnev="kovacsgergely" olvID="1" eolvID="1" onkurzusID="1">
            <nev>Kovács Gergely</nev>
            <szulIdo>1990-01-01</szulIdo>
            <lakcim>
                <irsz>3500</irsz>
                <varos>Miskolc</varos>
                <utca>Béla utca 3.</utca>
            </lakcim>
        </tanulo>
        <tanulo felhID="2" felhnev="kissjanos" olvID="2" eolvID="2" onkurzusID="2">
            <nev>Kiss János</nev>
            <szulIdo>1991-02-02</szulIdo>
            <lakcim>
                <irsz>3500</irsz>
                <varos>Miskolc</varos>
                <utca>Deák utca 5.</utca>
            </lakcim>
        </tanulo>
        <tanulo felhID="3" felhnev="nagypeter" olvID="3" eolvID="3" onkurzusID="3">
            <nev>Nagy Péter</nev>
            <szulIdo>1992-03-03</szulIdo>
            <lakcim>
                <irsz>3500</irsz>
                <varos>Miskolc</varos>
                <utca>Erzsébet utca 7.</utca>
            </lakcim>
        </tanulo>
        <tanulo felhID="4" felhnev="kisgizi" olvID="4" eolvID="4" onkurzusID="4">
            <nev>Kis Gizella</nev>
            <szulIdo>1995-01-01</szulIdo>
            <lakcim>
                <irsz>3500</irsz>
                <varos>Miskolc</varos>
                <utca>Béla utca 3.</utca>
            </lakcim>
        </tanulo>
    </tanulok>
    <konyvek>
        <konyv kID="1" nyID="1">
            <szerzo>Neil Bradley</szerzo>
            <cim>Az XML-kézikönyv</cim>
            <kiado>Szak kiadó</kiado>
            <megjelenEv>2000</megjelenEv>
            <kategoria>Adatkezelés</kategoria>
            <kategoria>Web</kategoria>
            <kategoria>XML</kategoria>
        </konyv>
        <konyv kID="2" nyID="1">
            <szerzo>Jeffrey D. Ullmann</szerzo>
            <szerzo>Jennifer Widom</szerzo>
            <cim>Adatbázis-rendszerek - Alapvetés</cim>
            <kiado>Panem</kiado>
            <megjelenEv>2009</megjelenEv>
            <kategoria></kategoria>
        </konyv>
        <!-- <konyv kID="3" nyID="1">
            <szerzo></szerzo>
            <cim></cim>
            <kiado></kiado>
            <megjelenEv></megjelenEv>
            <kategoria></kategoria>
        </konyv>
        <konyv kID="4" nyID="1">
            <szerzo></szerzo>
            <cim></cim>
            <kiado></kiado>
            <megjelenEv></megjelenEv>
            <kategoria></kategoria>
        </konyv> -->
    </konyvek>
    <olvasas>
        <olvas olvasID="1" felhID="1" kID="1">
            <kezdete>2021-01-01</kezdete>
            <vege>2021-01-31</vege>
        </olvas>
        <olvas olvasID="2" felhID="2" kID="1">
            <kezdete>2021-01-01</kezdete>
            <vege>2021-01-31</vege>
        </olvas>
        <olvas olvasID="3" felhID="3" kID="1">
            <kezdete>2021-01-01</kezdete>
            <vege>2021-01-31</vege>
        </olvas>
        <olvas olvasID="4" felhID="4" kID="1">
            <kezdete>2021-01-01</kezdete>
            <vege>2021-01-31</vege>
        </olvas>
    </olvasas>
    <eolvasas>
        <ebook eID="1" nyID="2">
            <szerzo>Sashi Banzal</szerzo>
            <cim>XML Basics</cim>
            <kiado>Mercury Learning and Information</kiado>
            <megjelenEv>2020</megjelenEv>
            <link>https://www.packtpub.com/en-hu/product/xml-basics-9781836648741</link>
        </ebook>
        <!-- <ebook eID="2" nyID="2">
            <szerzo></szerzo>
            <cim></cim>
            <kiado></kiado>
            <megjelenEv></megjelenEv>
            <link></link>
        </ebook>
        <ebook eID="3" nyID="2">
            <szerzo></szerzo>
            <cim></cim>
            <kiado></kiado>
            <megjelenEv></megjelenEv>
            <link></link>
        </ebook>
        <ebook eID="4" nyID="2">
            <szerzo></szerzo>
            <cim></cim>
            <kiado></kiado>
            <megjelenEv></megjelenEv>
            <link></link>
        </ebook> -->
    </eolvasas>
    <onkurzusok>
        <onkurzus oID="1" nyID="2">
            <cim>XML Mastery: Unleashing the Power of Data Markup</cim>
            <kiado>EDUCBA Bridging the Gap</kiado>
            <megjelenEv>2024</megjelenEv>
            <link>https://www.udemy.com/course/xml-novice-to-ninja/</link>
        </onkurzus>
        <onkurzus oID="2" nyID="2">
            <cim>XML Essentials: Structure and Share Data Efficiently.</cim>
            <kiado>Faris Azam</kiado>
            <megjelenEv>2024</megjelenEv>
            <link>https://www.udemy.com/course/xml-essentials-structure-and-share-data-efficiently/</link>
        </onkurzus>
        <!-- <onkurzus oID="3" nyID="2">
            <cim></cim>
            <kiado></kiado>
            <megjelenEv></megjelenEv>
            <link></link>
        </onkurzus>
        <onkurzus oID="4" nyID="2">
            <cim></cim>
            <kiado></kiado>
            <megjelenEv></megjelenEv>
            <link></link>
        </onkurzus> -->
    </onkurzusok>
    <oktatok>
        <oktato oktID="1">
            <nev></nev>
            <email></email>
            <weboldal></weboldal>
        </oktato>
        <oktato oktID="2">
            <nev></nev>
            <email></email>
            <weboldal></weboldal>
        </oktato>
        <oktato oktID="3">
            <nev></nev>
            <email></email>
            <weboldal></weboldal>
        </oktato>
        <oktato oktID="4">
            <nev></nev>
            <email></email>
            <weboldal></weboldal>
        </oktato>
    </oktatok>
    <nyelvek>
        <nyelv nyID="1">
            <nev>Magyar</nev>
        </nyelv>
        <nyelv nyID="2">
            <nev>Angol</nev>
        </nyelv>
        <nyelv nyID="3">
            <nev>Német</nev>
        </nyelv>
    </nyelvek>
</oktatas>

=== kovacsgergely22/Notes/Web/XML_ME/Webes_adatkezelo_kornyezetek/Feleves_feladat/ModifiedXMLmktjs0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><oktatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDmktjs0.xsd">
    <tanulok>
        <tanulo felhID="FELH0001" felhnev="kovacsgergely">
            <nev>Kovács Gergely</nev>
            <szulIdo>1990-01-01</szulIdo>
            <lakcim>
                <irsz>3500</irsz>
                <varos>Miskolc</varos>
                <utca>Béla utca 3.</utca>
            </lakcim>
        </tanulo>
        <tanulo felhID="FELH0002" felhnev="kissjanos">
            <nev>Kiss János</nev>
            <szulIdo>1991-02-02</szulIdo>
            <lakcim>
                <irsz>3500</irsz>
                <varos>Miskolc</varos>
                <utca>Deák utca 5.</utca>
            </lakcim>
        </tanulo>
        <tanulo felhID="FELH0003" felhnev="nagypeter">
            <nev>Nagy Péter</nev>
            <szulIdo>1992-03-03</szulIdo>
            <lakcim>
                <irsz>3500</irsz>
                <varos>Miskolc</varos>
                <utca>Erzsébet utca 7.</utca>
            </lakcim>
        </tanulo>
        <tanulo felhID="FELH0004" felhnev="kisgizi">
            <nev>Kis Gizella</nev>
            <szulIdo>1995-01-01</szulIdo>
            <lakcim>
                <irsz>3500</irsz>
                <varos>Miskolc</varos>
                <utca>Béla utca 3.</utca>
            </lakcim>
        </tanulo>
    </tanulok>
    <konyvek>
        <konyv kID="K0001" nyID="NY0001">
            <szerzo>Neil Bradley</szerzo>
            <cim>Az XML-kézikönyv</cim>
            <kiado>Szak kiadó</kiado>
            <megjelenEv>2000</megjelenEv>
            <kategoria>Adatkezelés</kategoria>
            <kategoria>Web</kategoria>
            <kategoria>XML</kategoria>
        </konyv>
        <konyv kID="K0002" nyID="NY0001">
            <szerzo>Jeffrey D. Ullmann</szerzo>
            <szerzo>Jennifer Widom</szerzo>
            <cim>Adatbázis-rendszerek - Alapvetés</cim>
            <kiado>Panem</kiado>
            <megjelenEv>2009</megjelenEv>
            <kategoria/>
        </konyv>
        <konyv kID="K0003" nyID="NY0001">
            <szerzo>Kövesdán Gábor</szerzo>
            <cim>Szoftverfejlesztés Java SE platformon</cim>
            <kiado/>
            <megjelenEv>2014</megjelenEv>
            <kategoria>Java</kategoria>
        </konyv>
        <konyv kID="K0004" nyID="NY0001">
            <szerzo>Thomas H. Cormen</szerzo>
            <szerzo>Charles E. Leiserson</szerzo>
            <szerzo>Ronald L. Rivest</szerzo>
            <cim>Algoritmusok</cim>
            <kiado>Műszaki Könyvkiadó</kiado>
            <megjelenEv>2003</megjelenEv>
            <kategoria>Algoritmusok</kategoria>
        </konyv>
    </konyvek>
    <olvasas>
        <olvas felhID="FELH0001" kID="K0001" olvasID="OLVAS0001">
            <kezdete>2021-01-01</kezdete>
            <vege>2021-01-31</vege>
        </olvas>
        <olvas felhID="FELH0002" kID="K0001" olvasID="OLVAS0002">
            <kezdete>2021-01-01</kezdete>
            <vege>2021-01-31</vege>
        </olvas>
        <olvas felhID="FELH0003" kID="K0001" olvasID="OLVAS0003">
            <kezdete>2021-01-01</kezdete>
            <vege>2021-01-31</vege>
        </olvas>
        <olvas felhID="FELH0004" kID="K0001" olvasID="OLVAS0004">
            <kezdete>2021-01-01</kezdete>
            <vege>2021-01-31</vege>
        </olvas>
    </olvasas>
    <eolvasas>
        <ebook eID="E0001" nyID="NY0002">
            <szerzo>Sashi Banzal</szerzo>
            <cim>XML Basics</cim>
            <kiado>Mercury Learning and Information</kiado>
            <megjelenEv>2020</megjelenEv>
            <link>https://www.packtpub.com/en-hu/product/xml-basics-9781836648741</link>
        </ebook>
        <ebook eID="E0002" nyID="NY0002">
            <szerzo>Dr Adamkó Attila</szerzo>
            <cim>Fejlett adatbázis technológiák</cim>
            <kiado/>
            <megjelenEv>2013</megjelenEv>
            <link>https://dtk.tankonyvtar.hu/handle/123456789/12049</link>
        </ebook>
        <ebook eID="E0003" nyID="NY0002">
            <szerzo>Jeszenszky Péter</szerzo>
            <cim>XML sémanyelvek</cim>
            <kiado>Debreceni Egyetem</kiado>
            <megjelenEv>2010</megjelenEv>
            <link>https://arato.inf.unideb.hu/jeszenszky.peter/xml/book/#d6e30</link>
        </ebook>
        <ebook eID="E0004" nyID="NY0002">
            <szerzo>Kovács László</szerzo>
            <cim>XML technikák</cim>
            <kiado>Miskolci Egyetem</kiado>
            <megjelenEv>2011</megjelenEv>
            <link>https://dtk.tankonyvtar.hu/handle/123456789/12928</link>
        </ebook>
    </eolvasas>
    <onkurzusok>
        <onkurzus nyID="NY0002" oID="O0001">
            <cim>XML Mastery: Unleashing the Power of Data Markup</cim>
            <kiado>EDUCBA Bridging the Gap</kiado>
            <megjelenEv>2024</megjelenEv>
            <link>https://www.udemy.com/course/xml-novice-to-ninja/</link>
        </onkurzus>
        <onkurzus nyID="NY0002" oID="O0002">
            <cim>XML Essentials: Structure and Share Data Efficiently.</cim>
            <kiado>Faris Azam</kiado>
            <megjelenEv>2024</megjelenEv>
            <link>https://www.udemy.com/course/xml-essentials-structure-and-share-data-efficiently/</link>
        </onkurzus>
        <onkurzus nyID="NY0002" oID="O0003">
            <cim>XML and XSD: a complete W3C-content based course (+10 hours)</cim>
            <kiado>Daniel Pinheiro Maia</kiado>
            <megjelenEv>2019</megjelenEv>
            <link>https://www.udemy.com/course/xml-and-xsd-a-complete-w3c-content-based-course/</link>
        </onkurzus>
        <onkurzus nyID="NY0002" oID="O0004">
            <cim>Data Representation and Serialization</cim>
            <kiado>ITPro TV</kiado>
            <megjelenEv>2019</megjelenEv>
            <link>https://www.udemy.com/course/data-representation-and-serialization/?couponCode=KEEPLEARNING</link>
        </onkurzus>
    </onkurzusok>
    <oktatok>
        <oktato oktID="OKT0001">
            <nev>Dr. Kovács Gergely</nev>
            <email/>
            <weboldal/>
        </oktato>
        <oktato oktID="OKT0002">
            <nev/>
            <email>kovacs.gergely@example.com</email>
            <weboldal/>
        </oktato>
        
        <oktato oktID="OKT0004">
            <nev/>
            <email/>
            <weboldal/>
        </oktato>
    </oktatok>
    <nyelvek>
        <nyelv nyID="NY0001">
            <nev>Spanyol</nev>
        </nyelv>
        <nyelv nyID="NY0002">
            <nev>Angol</nev>
        </nyelv>
        <nyelv nyID="NY0003">
            <nev>Német</nev>
        </nyelv>
    <nyelv nyID="NY0004"><nev>Francia</nev></nyelv></nyelvek>
</oktatas>
